version: '3.7'

services:
  hexin-gateway:
    image: hexin-gateway
    container_name: hexin-gateway
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      args:
        - PORT=8000
    links:
      - rabbitmq
    ports:
      - 8000:8000
      - 9228:9229
    volumes:
      - ../../:/usr/src/app
    env_file:
      - ../../.env
    environment:
      - PORT=8000
      - NODE_ENV=development
    command: nodemon --config nodemon.json
    networks:
      - services
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
    networks:
      - services

networks:
  services:
    name: services